### ISSUE TITLE
Shouldn't the executed command be binocular-cli

### ISSUE THREAD

**Issue by suiramdev** [jpcrs/binocular#1]
Hi, I tried to use the package, but I noticed that the command executed from the extension is `binocular-rust`.
I think it is supposed to be `binocular-cli`. Am I doing something wrong?

**Comment by jpcrs** [comment]
Oops, you're not doing anything wrong.

Since I though no one would download this, I didn't test it properly (ofc), and I have both binaries (-cli and -rust) in my machine :))

I also have no idea how the binary will behave in different OSes, so feel free to report if anything goes wrong.

Publishing v0.0.5 with your fix.

**Comment by suiramdev** [comment]
Ahah! Good for you to see that there is interest. Being a fan of neovim, I needed to find a similar experience on vscode.
Thank you for your attention and your responsiveness. Indeed, I am on MacOSx and it seems to me that the binocular-cli package (obviously depreciated) uses this command by default.
